// Generated by CoffeeScript 1.8.0
(function() {
  var ConnRequest, ServerConn, uuid;

  uuid = require("node-uuid");

  ServerConn = require("./ServerConn");

  module.exports = ConnRequest = (function() {
    function ConnRequest(httpRequest, httpResponse, chainedApps) {
      this.httpRequest = httpRequest;
      this.httpResponse = httpResponse;
      this.chainedApps = chainedApps;
    }

    ConnRequest.prototype.accept = function() {
      var sessid;
      sessid = uuid.v1();
      this.httpResponse.writeHead(200, {
        'x-htunsess': sessid
      });
      this.httpResponse.end();
      return new ServerConn(sessid, this.chainedApps, this.httpRequest);
    };

    ConnRequest.prototype.reject = function(httpSatusCode, msg) {
      this.httpResponse.writeHead(httpSatusCode, {
        'x-htunrejectmsg': msg
      });
      return this.httpResponse.end();
    };

    return ConnRequest;

  })();

}).call(this);

//# sourceMappingURL=ConnRequest.js.map
