// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    BlockSize: 500000,
    AutoSealDelayMs: 20,
    ReqOpenIntervalMs: 5000
  };

}).call(this);

//# sourceMappingURL=Constants.js.map
