// Generated by CoffeeScript 1.8.0
(function() {
  var ConnRequest, Server,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ConnRequest = require('./ConnRequest');

  module.exports = Server = (function(_super) {
    __extends(Server, _super);

    function Server(chainedApps) {
      this.chainedApps = chainedApps;
      this.chainedApps.add((function(_this) {
        return function(req, res, next) {
          if ('conn' === req.headers['x-htundir']) {
            return _this.emit('request', new ConnRequest(req, res, _this.chainedApps));
          } else {
            return next();
          }
        };
      })(this));
    }

    return Server;

  })(require('events').EventEmitter);

}).call(this);

//# sourceMappingURL=Server.js.map
