// Generated by CoffeeScript 1.8.0
(function() {
  var log;

  log = require("lawg");

  module.exports = {
    isDebug: process.env['NODE_DEBUG'] && /wstunnel/.test(process.env['NODE_DEBUG'])
  };

  if (module.exports.isDebug) {
    module.exports.log = function(msg) {
      return log(msg);
    };
  } else {
    module.exports.log = function() {};
  }

}).call(this);

//# sourceMappingURL=debug.js.map
