// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    toEtag: function(headers) {
      return 'W/"' + (new Buffer(JSON.stringify(headers)).toString('base64')) + '"';
    },
    fromEtag: function(etag) {
      etag = etag.slice(3, etag.length - 1);
      return JSON.parse(new Buffer(etag, "base64").toString('utf8'));
    }
  };

}).call(this);

//# sourceMappingURL=etagHeader.js.map
