// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(httpRequest) {
    return httpRequest.headers['x-forwarded-for'] || httpRequest.connection.remoteAddress || httpRequest.socket.remoteAddress || httpRequest.connection.socket.remoteAddress;
  };

}).call(this);

//# sourceMappingURL=httpReqRemoteIp.js.map
