// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    server: require("./wst_server"),
    client: require("./wst_client")
  };

}).call(this);

/*
//@ sourceMappingURL=wst.map
*/
