// Generated by CoffeeScript 1.7.1
(function() {
  var WebSocketClient, bindSockets, net, wst_client;

  WebSocketClient = require('websocket').client;

  net = require("net");

  bindSockets = require("./bindSockets");

  module.exports = wst_client = (function() {
    function wst_client() {
      this.tcpServer = net.createServer();
    }

    wst_client.prototype.start = function(localPort, wsHostUrl, remoteAddr) {
      this.tcpServer.listen(localPort);
      return this.tcpServer.on("connection", (function(_this) {
        return function(tcpConn) {
          var url, wsClient;
          console.log("Connection detected");
          wsClient = new WebSocketClient();
          wsClient.on('connectFailed', function(error) {
            console.log('WS connect error: ' + error.toString());
            return tcpConn.destroy();
          });
          wsClient.on('connect', function(wsConn) {
            console.log('WebSocket connected, binding tunnel');
            return bindSockets(wsConn, tcpConn);
          });
          if (remoteAddr) {
            url = "" + wsHostUrl + "/?dst=" + remoteAddr;
          } else {
            url = "" + wsHostUrl;
          }
          return wsClient.connect(url, 'tunnel-protocol');
        };
      })(this));
    };

    return wst_client;

  })();

}).call(this);

//# sourceMappingURL=wst_client.map
