//@ sourceMappingURL=wst_client.map
// Generated by CoffeeScript 1.6.1
(function() {
  var WebSocketClient, bindSockets, net, wst_client;

  WebSocketClient = require('websocket').client;

  net = require("net");

  bindSockets = require("./bindSockets");

  /*
  argv = require('optimist')
      .usage('Usage: $0 -x [num] -y [num]')
      .demand(['x','y'])
      .argv;
  */


  module.exports = wst_client = (function() {

    function wst_client() {
      this.tcpServer = net.createServer();
      this.wsClient = new WebSocketClient();
    }

    wst_client.prototype.start = function(localPort, wsHostUrl, remoteAddr) {
      var _this = this;
      this.tcpServer.listen(localPort);
      return this.tcpServer.on("connection", function(tcpConn) {
        var url;
        console.log("Connection detected");
        _this.wsClient.on('connectFailed', function(error) {
          console.log('WS connect error: ' + error.toString());
          return tcpConn.destroy();
        });
        _this.wsClient.on('connect', function(wsConn) {
          console.log('WebSocket connected, binding tunnel');
          return bindSockets(wsConn, tcpConn);
        });
        if (remoteAddr) {
          url = "" + wsHostUrl + "/?dst=" + remoteAddr;
        } else {
          url = "" + wsHostUrl;
        }
        return _this.wsClient.connect(url, 'tunnel-protocol');
      });
    };

    return wst_client;

  })();

}).call(this);
